name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      working-directory: ./src
      run: make
    - name: make web
      run: |
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk
        ./emsdk install latest
        ./emsdk activate latest
        source ./emsdk_env.sh
        cd ../src
        mkdir ../build
        make web
    - name: make check
      working-directory: ./src
      run: make check
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: build
        
  #  - name: Automatic Pre-Releases
  #    uses: marvinpinto/action-automatic-releases@v1.2.1
  #    with:
  #      # GitHub secret token
  #      repo_token: "${{ secrets.GITHUB_TOKEN }}"
  #      # Git tag (for automatic releases)
  #      automatic_release_tag: "latest"
  #      # Should this release be marked as a draft?
  #      draft: true
  #      # Should this release be marked as a pre-release?
  #      prerelease: true
  #      # Release title (for automatic releases)
  #      title: "Development Build"
  #      # Assets to upload to the release
  #      files: build
        
#    - name: Push .data to React repo
#      uses: dmnemec/copy_file_to_another_repo_action@main
#      env:
#        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
#      with:
#        source_file: 'build/web_amr_prediction.data'
#        destination_repo: 'bacpop/AMR_ReactApp'
#        destination_branch: 'dev'
#        destination_folder: 'public'
#        user_email: ${{ secrets.SECRET_M }}
#        user_name: ${{ secrets.SECRET_N }}
#        commit_message: 'Update to most recent version of WebAssembly code'
        
    # - name: Push .data to React repo and create pull request
    #   uses: paygoc6/action-pull-request-another-repo@v1.0.1
    #   env:
    #     API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
    #   with:
    #     source_folder: 'build/web_amr_prediction.data'
    #     destination_repo: 'bacpop/AMR_ReactApp'
    #     destination_folder: 'public'
    #     destination_base_branch: 'main'
    #     destination_head_branch: 'dev'
    #     user_email: ${{ secrets.SECRET_M }}
    #     user_name: ${{ secrets.SECRET_N }}
        
    # - name: Push.wasm to React repo
    #   uses: dmnemec/copy_file_to_another_repo_action@main
    #   env:
    #     API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
    #   with:
    #     source_file: 'build/web_amr_prediction.wasm'
    #     destination_repo: 'bacpop/AMR_ReactApp'
    #     destination_branch: 'dev'
    #     destination_folder: 'public'
    #     user_email: ${{ secrets.SECRET_M }}
    #     user_name: ${{ secrets.SECRET_N }}
    #     commit_message: 'Update to most recent version of WebAssembly code'
       
    # - name: Push .js to React repo
    #   uses: dmnemec/copy_file_to_another_repo_action@main
    #   env:
    #     API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
    #   with:
    #     source_file: 'build/web_amr_prediction.js'
    #     destination_repo: 'bacpop/AMR_ReactApp'
    #     destination_branch: 'dev'
    #     destination_folder: 'public'
    #     user_email: ${{ secrets.SECRET_M }}
    #     user_name: ${{ secrets.SECRET_N }}
    #     commit_message: 'Update to most recent version of WebAssembly code'
     
